SeleniumQALight/G32Project

- chernenkoProj/pom.xml
- chernenkoProj/src/main/java/chernenkoProj/App.java
- chernenkoProj/src/test/java/chernenkoProj/AppTest.java
- ischukProj/pom.xml
- ischukProj/src/main/java/ischukProj/App.java
- ischukProj/src/test/java/ischukProj/AppTest.java
- pom.xml
> New proj chernenko and ischuk

- mokliakProj/src/test/java/mokliakProj/AppTest.java
> Mokliak 22 03

- IschukTestGit
> Ischuk 22 03

- vingenterProj/src/test/java/vingenterProj/AppTest.java
> Vinhenter 2203

- cherkezProj/src/test/java/cherkezProj/AppTest.java
> Cherkez 22 03

- chernoivanovaProj/src/test/java/chernoivanovaProj/AppTest.java
> Chornoivanova 22 03

- naumiakProj/src/test/java/naumiakProj/AppTest.java
> Naumiak 22 03

- levitskiiProj/src/test/java/levitskiiProj/AppTest.java
> Levitskiy 22 03

- demkoProj/src/test/java/demkoProj/AppTest.java
> Demko 22.03

- overAll/src/test/java/overAll/AppTest.java
> Radulenko 22 03

- zhurbaProj/src/test/java/zhurbaProj/AppTest.java
> Zhurba 22 03

- velichkoProj/src/test/java/velichkoProj/AppTest.java
> Velichko 22 03

- chichikProj/src/test/java/chichikProj/AppTest.java
> Chichick 22 03

- bikovProj/src/test/java/bikovProj/AppTest.java
> Bykov 22 03

- zhurbaProj/src/TC_for_v3.test.txt
- zhurbaProj/src/test/java/zhurbaProj/AppTest.java
> Homework_22.03.2018

- mokliakProj/src/mokliak_22-03-18HW
> mokliak_22-03-18HW

- shylinaProj/src/test/java/shylinaProj/AppTest.java
> Shylina 22 03

- chernenkoProj/src/test case 1
- chernenkoProj/src/test case 2
- chernenkoProj/src/test case 3
- chernenkoProj/src/test case 4
- chernenkoProj/src/test case 5
> test cases 5

- chichikProj/src/test/java/chichikProj/AppTest.java
@tradulenko Please review pull request
> test commit for git testing

- chernoivanovaProj/src/test/java/chernoivanovaProj/AppTest.java
> second commit 2

- zhurbaProj/src/test/java/zhurbaProj/AppTest.java
> zhurba_27.03.2018

- chichikProj/src/test/java/chichikProj/AppTest.java
@tradulenko Please review or ignore
> test commit for git testing new

- velichkoProj/src/test/java/velichkoProj/AppTest.java
> first commit 3

- petrinaProj/src/Test Cases
> Petrina 22 03

- shylinaProj/src/test/java/shylinaProj/AppTest.java
> test push 27/03

- levitskiiProj/src/test/java/levitskiiProj/AppTest.java
> Take these changes

- naumiakProj/src/test/java/naumiakProj/AppTest.java
> commit file with new comment

- demkoProj/src/test/java/demkoProj/AppTest.java
> first commit 2

- teslenkoProj/pom.xml
- teslenkoProj/src/test/java/loginTests/LogIn.java
> login test

- chernenkoProj/src/UIMapping.properties
- chernenkoProj/src/locators
- chernenkoProj/src/ts6-back to main page
> ts6 was modified, new locators

- chernenkoProj/pom.xml
- chernenkoProj/src/test/java/loginTests/Login.java
> Chernenko 10 04 2018 1

- chaikaProj/pom.xml
- chaikaProj/src/UIMapping.properties
- chaikaProj/src/test/java/loginTests/LogIn.java
> First test login test

- sameliukProj/pom.xml
- sameliukProj/src/test/java/loginTests/Login.java
> commit loginTest

- cherkezProj/pom.xml
- cherkezProj/src/log4j.properties
- cherkezProj/src/main/java/libs/ActionsWithOurElements.java
- cherkezProj/src/main/java/pages/LoginPage.java
- cherkezProj/src/main/java/pages/ParentPage.java
- cherkezProj/src/test/java/loginTests/LogIn.java
- cherkezProj/src/test/java/loginTests/LoginTestWithPageObject.java
- cherkezProj/src/test/java/parentTest/ParentTest.java
> login-autotest

- ischukProj/src/TC1
- ischukProj/src/TC2
- ischukProj/src/TC3
- ischukProj/src/TC4
- ischukProj/src/TC5
> Ischuk 15 04

- chichikProj/pom.xml
- chichikProj/src/log4j.properties
- chichikProj/src/main/java/libs/ActionsWithOurElements.java
- chichikProj/src/main/java/pages/LoginPage.java
- chichikProj/src/main/java/pages/parentPage.java
- chichikProj/src/test/java/loginTests/LogIn.java
- chichikProj/src/test/java/loginTests/LoginTestWithPageObject.java
- chichikProj/src/test/java/parentTest/ParentTest.java
> project structure created

- zhilaProj/pom.xml
- zhilaProj/src/log4j.properties
- zhilaProj/src/main/java/libs/ActionWithOurElements.java
- zhilaProj/src/main/java/pages/LoginPage.java
- zhilaProj/src/main/java/pages/ParentPage.java
- zhilaProj/src/test/java/loginTests/LogIn.java
- zhilaProj/src/test/java/loginTests/LogInTestWithPageObject.java
- zhilaProj/src/test/java/parentTest/ParentTest.java
> Mzhyla 20180412

- zhilaProj/pom.xml
- zhilaProj/src/test/java/loginTests/LogIn.java
> Create login test

- teslenkoProj/pom.xml
- teslenkoProj/src/log4j.properties
- teslenkoProj/src/main/java/libs/ActionsWithOurElements.java
- teslenkoProj/src/main/java/pages/LoginPage.java
- teslenkoProj/src/main/java/pages/ParentPage.java
- teslenkoProj/src/test/java/loginTests/LogIn.java
- teslenkoProj/src/test/java/loginTests/LoginTestWithPageObject.java
- teslenkoProj/src/test/java/parentTest/ParentTest.java
- teslenkoProj/src/test/java/teslenkoProj/AppTest.java
> 12-04-test with page object

- chernenkoProj/pom.xml
- chernenkoProj/src/log4j.properties
- chernenkoProj/src/main/java/libs/ActionWithOurElements.java
- chernenkoProj/src/main/java/pages/LoginPage.java
- chernenkoProj/src/main/java/pages/ParentPage.java
- chernenkoProj/src/test/java/loginTests/LoginTestWithPageObject.java
- chernenkoProj/src/test/java/parentTest/ParentTest.java
> test with page object

- sameliukProj/pom.xml
- sameliukProj/src/log4j.properties
- sameliukProj/src/main/java/newLibs/ActionsWithOurElements.java
- sameliukProj/src/main/java/pages/LoginPage.java
- sameliukProj/src/main/java/pages/ParentPage.java
- sameliukProj/src/test/java/loginTests/LoginTestWithPageObject.java
- sameliukProj/src/test/java/parentTest/PaentTest.java
> commit loginTestWithPageobject

- zhurbaProj/src/main/java/libs/ActionsWithOurElements.java
- zhurbaProj/src/main/java/pages/LoginPage.java
- zhurbaProj/src/test/java/loginTests/LoginTestWithPageObject.java
@tradulenko Hi, Taras! 
Could you please approve current pull request.
I've added two methods - 'enterPassword' and 'clickOntoBxod'.
> Zhurba hw 12042018

- zhilaProj/src/main/java/libs/ActionWithOurElements.java
- zhilaProj/src/main/java/pages/LoginPage.java
- zhilaProj/src/test/java/loginTests/LogInTestWithPageObject.java
@tradulenko 
Updated ActionWithElements, LoginPage and LoginTestWithPageObject classes
> Mzhyla 20180416

- overAll/pom.xml
- overAll/src/log4j.properties
- overAll/src/main/java/libs/ActionsWithOurElements.java
- overAll/src/main/java/pages/LoginPage.java
- overAll/src/main/java/pages/ParentPage.java
- overAll/src/test/java/loginTests/LoginTestWithPageObject.java
- overAll/src/test/java/parentTest/ParentTest.java
> test with pageObject

- overAll/pom.xml
- overAll/src/main/java/RestSteps/MainRestSteps.java
- overAll/src/main/java/libs/CurrencyValues.java
- overAll/src/main/java/libs/ResponseStructureForRestAssuredTest.java
- overAll/src/main/java/libs/Utils.java
- overAll/src/test/java/restTest/TestRestAssured.java
- overAll/src/test/java/restTest/linksForRestAssured
> work with Rest Was added

- overAll/src/main/java/libs/ActionsWithOurElements.java
- overAll/src/main/java/pages/EditeSparesPage.java
- overAll/src/main/java/pages/HomePage.java
- overAll/src/main/java/pages/LoginPage.java
- overAll/src/main/java/pages/ParentPage.java
- overAll/src/main/java/pages/SparesPage.java
- overAll/src/test/java/loginTests/LoginTestWithPageObject.java
- overAll/src/test/java/parentTest/ParentTest.java
- overAll/src/test/java/spareTest/AddNewSpareTest.java
> Radulenko 17 04

- chernenkoProj/src/main/java/libs/ActionWithOurElements.java
- chernenkoProj/src/main/java/pages/EditProvidersPage.java
- chernenkoProj/src/main/java/pages/EditSparesPage.java
- chernenkoProj/src/main/java/pages/HomePage.java
- chernenkoProj/src/main/java/pages/LoginPage.java
- chernenkoProj/src/main/java/pages/ParentPage.java
- chernenkoProj/src/main/java/pages/ProvidersPage.java
- chernenkoProj/src/main/java/pages/SparesPage.java
- chernenkoProj/src/test/java/loginTests/LoginTestWithPageObject.java
- chernenkoProj/src/test/java/parentTest/ParentTest.java
- chernenkoProj/src/test/java/providersTest/AddNewProviderTest.java
- chernenkoProj/src/test/java/spareTest/AddNewSpareTest.java
> Chernenko 17 04

- zhilaProj/src/main/java/libs/ActionWithOurElements.java
- zhilaProj/src/main/java/pages/EditSparesPage.java
- zhilaProj/src/main/java/pages/HomePage.java
- zhilaProj/src/main/java/pages/LoginPage.java
- zhilaProj/src/main/java/pages/ParentPage.java
- zhilaProj/src/main/java/pages/SparesPage.java
- zhilaProj/src/test/java/checkboxTest/checkboxTest.java
- zhilaProj/src/test/java/loginTests/LogIn.java
- zhilaProj/src/test/java/loginTests/LogInTestWithPageObject.java
- zhilaProj/src/test/java/parentTest/ParentTest.java
- zhilaProj/src/test/java/spareTest/AddNewSpareTest.java
Updated LoginTests classes @tradulenko
> Mzhyla 20180417

- zhurbaProj/src/main/java/libs/ActionsWithOurElements.java
- zhurbaProj/src/main/java/pages/DealSidesPage.java
- zhurbaProj/src/main/java/pages/EditDealSidesPage.java
- zhurbaProj/src/main/java/pages/EditSparesPage.java
- zhurbaProj/src/main/java/pages/HomePage.java
- zhurbaProj/src/main/java/pages/LoginPage.java
- zhurbaProj/src/main/java/pages/ParentPage.java
- zhurbaProj/src/main/java/pages/SparesPage.java
- zhurbaProj/src/test/java/dealSidesTest/AddNewDealSide.java
- zhurbaProj/src/test/java/loginTests/LoginTestWithPageObject.java
- zhurbaProj/src/test/java/parentTest/ParentTest.java
- zhurbaProj/src/test/java/spareTest/AddNewSpareTest.java
@tradulenko Hi Taras. Please approve my current pull request.
I've watched last lesson on YouTube and repeat the whole lesson work.
> Zhurba 17 04

- petrinaProj/src/main/java/libs/ActionsWithOurElements.java
- petrinaProj/src/main/java/pajes/EditSparesPage.java
- petrinaProj/src/main/java/pajes/HomePage.java
- petrinaProj/src/main/java/pajes/LoginPage.java
- petrinaProj/src/main/java/pajes/ParentPage.java
- petrinaProj/src/main/java/pajes/SparesPage.java
- petrinaProj/src/test/java/logintests/LoginTestWithPageObject.java
- petrinaProj/src/test/java/parentTest/ParentTest.java
- petrinaProj/src/test/java/spareTest/AddNewSpareTest.java
> Petrina 17 04

- sameliukProj/src/HomeWork11_Locators
- sameliukProj/src/main/java/newLibs/ActionsWithOurElements.java
- sameliukProj/src/main/java/pages/EditSparesPage.java
- sameliukProj/src/main/java/pages/HomePage.java
- sameliukProj/src/main/java/pages/LoginPage.java
- sameliukProj/src/main/java/pages/ParentPage.java
- sameliukProj/src/main/java/pages/SparesPage.java
- sameliukProj/src/test/java/loginTests/LoginTestWithPageObject.java
- sameliukProj/src/test/java/parentTest/ParentTest.java
- sameliukProj/src/test/java/spareTest/AddNewSpareTest.java
> Commit Avatar

- chernenkoProj/src/main/java/libs/ActionWithOurElements.java
- chernenkoProj/src/main/java/pages/EditProvidersPage.java
- chernenkoProj/src/main/java/pages/EditSparesPage.java
- chernenkoProj/src/main/java/pages/ProvidersPage.java
- chernenkoProj/src/main/java/pages/SparesPage.java
- chernenkoProj/src/test/java/providersTest/AddNewProviderTest.java
- chernenkoProj/src/test/java/spareTest/AddNewSpareTest.java
> Chernenko 22 04

- naumiakProj/src/main/java/libs/ActionsWithOurElements.java
- naumiakProj/src/main/java/pages/EditSapresPage.java
- naumiakProj/src/main/java/pages/HomePage.java
- naumiakProj/src/main/java/pages/LoginPage.java
- naumiakProj/src/main/java/pages/ParentPage.java
- naumiakProj/src/main/java/pages/SparesPage.java
- naumiakProj/src/test/java/loginTests/LogIn.java
- naumiakProj/src/test/java/loginTests/LoginTestWithPageObject.java
- naumiakProj/src/test/java/parentTest/ParentTest.java
- naumiakProj/src/test/java/spareTest/AddNewSpareTest.java
> Naumiak 1704

- petrinaProj/src/main/java/libs/ActionsWithOurElements.java
- petrinaProj/src/main/java/pajes/EditSparesPage.java
- petrinaProj/src/main/java/pajes/HomePage.java
- petrinaProj/src/main/java/pajes/LoginPage.java
- petrinaProj/src/main/java/pajes/SparesPage.java
- petrinaProj/src/test/java/logintests/LoginTestWithParameters.java
- petrinaProj/src/test/java/parentTest/ParentTest.java
- petrinaProj/src/test/java/spareTest/AddNewSpareTest.java
> Petrina 27 04

- naumiakProj/src/main/java/libs/ActionsWithOurElements.java
> last lessons

- chaikaProj/pom.xml
- chaikaProj/src/main/java/libs/ConfigProperties.properties
- chaikaProj/src/main/java/libs/Database.java
- chaikaProj/src/main/java/libs/UtilsForDB.java
- chaikaProj/src/main/java/pages/LoginPage.java
- chaikaProj/src/test/java/dbTest/TestDB.java
- chaikaProj/src/test/java/parentTest/ParentTest.java
- chaikaProj/src/test/java/suits/SuitSmoke.java
> 08-05- SQL

- chernoivanovaProj/pom.xml
- chernoivanovaProj/src/main/java/pages/LoginPage.java
- chernoivanovaProj/src/test/java/loginTests/LoginTestWithPageObject.java
- chernoivanovaProj/src/test/java/parentTest/ParentTest.java
- chernoivanovaProj/src/test/java/suits/SuitSmoke.java
> Chornoivanova 10 05 maven reports screenshots

- zhurbaProj/pom.xml
- zhurbaProj/src/main/java/pages/LoginPage.java
- zhurbaProj/src/test/java/dbTest/TestDB.java
- zhurbaProj/src/test/java/loginTests/LoginTestWithPageObject.java
- zhurbaProj/src/test/java/parentTest/ParentTest.java
- zhurbaProj/src/test/java/suits/SuitSmoke.java
@tradulenko Hi Taras. Please approve this request.
> Zhurba 10.05

- chaikaProj/pom.xml
- chaikaProj/src/test/java/restTest/RestAssuredTest.java
- overAll/src/test/java/restTest/TestRestAssured.java
> Versia 17-05

- chernenkoProj/pom.xml
- chernenkoProj/src/main/java/pages/LoginPage.java
- chernenkoProj/src/test/java/dbTest/TestDB.java
- chernenkoProj/src/test/java/loginTests/LoginTestWithPageObject.java
- chernenkoProj/src/test/java/parentTest/ParentTest.java
- chernenkoProj/src/test/java/suits/SuitSmoke.java
> Chernenko 03 05

- chernenkoProj/pom.xml
- chernenkoProj/src/test/java/restTest/RestAssuredTest.java
> newRestTest
